### ISSUE TITLE
MEA FrostyModlManager error on Launch

### ISSUE THREAD

**Issue by oomek** [GalaxyEham/FrostyToolSuite#1]
```
Access to the path 'initfs_win32' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.Delete()
   at Frosty.ModSupport.FrostyModExecutor.RecursiveDeleteFiles(String path)
   at Frosty.ModSupport.FrostyModExecutor.DeleteSelectFiles(String modPath)
   at Frosty.ModSupport.FrostyModExecutor.<>c__DisplayClass17_0.<Run>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.<Run>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<launchButton_Click>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by GalaxyEham** [comment]
go to ur mass effect install dir right click on the folder, go to properties and untick read only, apply to all files and subfolders and try again. Also make sure that the mass effect executable is not running in the background (as a hung process).

**Comment by oomek** [comment]
That was it, thank You.
