### ISSUE TITLE
An unhandled exception has occurred - importing mods that are 7-zip compressed

### ISSUE THREAD

**Issue by Gr3yStar** [GalaxyEham/FrostyToolSuite#101]
Invalid Parameter

   at SevenZip.Compression.LZMA.Decoder.SetDecoderProperties(Byte[] properties)
   at FrostyModManager.Compression.SevenZipDecompressor.<EnumerateFiles>d__12.MoveNext()
   at FrostyModManager.MainWindow.<>c__DisplayClass25_0.<InstallMods>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<InstallMods>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

-----------------------------

A workaround is to simply extract and repackage the mod as .zip

**Comment by GalaxyEham** [comment]
Known issue
