### ISSUE TITLE
Mirror's Edge Catalyst Error

### ISSUE THREAD

**Issue by UpTwoEpoch** [GalaxyEham/FrostyToolSuite#102]
Mod Manager Version: 1.0.4
MEC Version: 1.3.47248
Replaced 'bcrypt.dll' with Frosty 1.0.3alpha4
Mods trying to use; Lighting Overhaul, Red Advertisements, Red Leaves, Red The View

I have followed the !permission MEC on the Discord server. Issue:

Access to the path 'chunks0.sb' is denied.

   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Frosty.ModSupport.FrostyModExecutor.‎⁮‫⁪‭‬⁪⁬​‭⁪‪⁪‫​⁪‮‌⁯‫⁭‮‎⁭⁫‭‍‍‎⁯⁪‍‌‌⁭⁫⁫⁫⁫‌‮(String )
   at Frosty.ModSupport.FrostyModExecutor.‫⁫‪​‬⁮⁬‮‎‭‭‮‍‮‬‫⁫⁪⁪‫‬⁪⁭‏‭‬‍⁫⁫⁬‭‎⁭‫‬​‍⁮‪‎‮(String )
   at Frosty.ModSupport.FrostyModExecutor.⁪‍‌⁮⁪‏‮‮⁪‬‭​‪⁫‬⁪⁭​‮‎‪‏‍‏‭​⁯⁬⁪‏⁫‌‫‫‮‏‪‫‫⁬‮.‏‬‎‍⁯⁪⁮‌⁫​⁭⁪‬‏⁭⁭‬⁯‬⁭‎⁬‍‫⁭‭‏‪​‎⁮⁬​‮‫‌‬‏‫‭‮()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.HKJ\*6@wc\]@%1Y3\\aUCr! MXH%.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GalaxyEham** [comment]
as per the !permission item:

Keep in mind that these fixes are not guaranteed to work. Every setup is different, so you might just have to mess around.
