### ISSUE TITLE
"Could not find a part of the path" with Admin rights

### ISSUE THREAD

**Issue by Wei-ss** [GalaxyEham/FrostyToolSuite#122]
Previous to this error, I was having problems with a Symlink error. I fixed that by creating the ModData folder myself in the ME:C directory, then launching through FMM. Since then I've been having trouble with two errors listed as 

```
Could not find a part of the path 'E:\Mirror's Edge - Catalyst\\moddata\patch\win32/gameconfigurations/initialinstallpackage/cas.cat'.
```
and
```
Could not find a part of the path 'E:\Mirror's Edge - Catalyst\ModData\Patch\win32\chunks0.sb'.
```
I read through the error compendium you listed, and set Frosty Mod Manager to Run as Administrator in the compatibility tab.  I also tried unchecking the Read-only flag on both the game directory and FMM directory, and taking ownership of both folders, but the problem persists.

I assume as both require to set proper permissions, that that's the problem, but I can't think of any other method I could go by.

Here's the full error, including the stack trace portion:
```
Could not find a part of the path 'E:\Mirror's Edge - Catalyst\\moddata\patch\win32/gameconfigurations/initialinstallpackage/cas.cat'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName)
   at Frosty.ModSupport.FrostyModExecutor.‫⁮‭‬​‭⁯‫‏⁯⁪‌‍⁫‏‭⁮⁬⁮‮⁫‭⁯⁪⁪‫‍‭⁬‮‎⁫‍‎⁪‍‪‭⁭⁬‮.⁮⁮‏⁪‫‮‮‌‪⁫‎‏‭⁮⁭‍⁭⁬‮‪‬‏‪‌‌​⁯‌‮‮‭⁭⁯⁬‍⁯‎‪‫‎‮()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.a??L-L?RY#(rdFBO%\[\[=$EX?\..MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Wei-ss** [comment]
Just an update. FMM seems to only have problems creating folders. I'm currently launching and creating folders it gives me errors for.
