### ISSUE TITLE
Error when loading BF1 meshes

### ISSUE THREAD

**Issue by Flandyn** [GalaxyEham/FrostyToolSuite#128]
Every time I try to load a mesh from Battlefield 1, I get this error:

```
Object reference not set to an instance of an object.

   at FrostyEditor.Controls.MeshPreviewScreen.LoadMesh(MeshSet mesh)
   at FrostyEditor.Controls.FrostyMeshSetEditor.<FrostyMeshSetEditor_Loaded>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by GalaxyEham** [comment]
I wouldnt at all be surprised if some meshes do not work, I havent tried the profile out in quite a while, tho just recently tested with the latest patch, and all meshes I opened, worked fine. So unless you can list some meshes that dont work, then I can only assume the issue is at your end.

Be aware that the profile has to be used with the latest version of Frosty as well, it will not work on any earlier versions.

**Comment by GalaxyEham** [comment]
yeah they all work fine here, even with the public version of Frosty v1.0.4.2, so something at your end
