### ISSUE TITLE
Value cannot be null, paramter name: buffer,  Mass effect andromeda

### ISSUE THREAD

**Issue by LifeReaper227** [GalaxyEham/FrostyToolSuite#131]
I did everything I could, started as administrator, changed the ownership of folders, both game and frosty, deleted bcrypt.dll, even re-installed the game and even tried all of the frosty versions. I searched for days, even this site does not have the answer. I can start the game by frosty when it has no mod active, but whenever it has a mod loaded, this happens:

Value cannot be null.
paramter name: buffer

   em System.Security.Cryptography.HashAlgorithm.ComputeHash(Byte[] buffer)
   em FrostySdk.Utils.GenerateSha1(Byte[] buffer)
   em Frosty.ModSupport.FrostyModExecutor.‫⁮‭‬​‭⁯‫‏⁯⁪‌‍⁫‏‭⁮⁬⁮‮⁫‭⁯⁪⁪‫‍‭⁬‮‎⁫‍‎⁪‍‪‭⁭⁬‮.⁮⁮‏⁪‫‮‮‌‪⁫‎‏‭⁮⁭‍⁭⁬‮‪‬‏‪‌‌​⁯‌‮‮‭⁭⁯⁬‍⁯‎‪‫‎‮()
   em System.Threading.Tasks.Task.Execute()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Frosty.ModSupport.FrostyModExecutor.a??L-L?RY#(rdFBO%\[\[=$EX?\..MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Please help

![sem titulo](https://user-images.githubusercontent.com/43818204/46417178-75327000-c6ff-11e8-94a1-b44051728fa5.png)

**Comment by cascardian** [comment]
I have nearly the same error, but now with **1.4.0.5** on W10 1809. Older versions, which used to work with MEA on 1803 via the bcrypt fix, show this as well. Tried everything except rolling back and I don't really want to do that, sorry. Rollout would have been for some limited population on Oct 3rd, so @LifeReaper227's report above could have been about 1809, even though they don't specify the Windows version. I don't know if this is the same issue as #132.

> Value cannot be null.
Parameter name: buffer
>
 >  at System.Security.Cryptography.HashAlgorithm.ComputeHash(Byte[] buffer)
   at FrostySdk.FYHvYggtQUaXgNffCLTiC.KhakaiTlSIItCTBbkPTkMujBL(Byte[] lxoPtJsHAIsroVYlY)
   at Frosty.ModSupport.FrostyModExecutor.<>c__DisplayClass25_0.<TUyxjeaURbVvnXKuniMdAiIYjMUMbPiw>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.<TUyxjeaURbVvnXKuniMdAiIYjMUMbPiw>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<TmqvxvegIJHeApBhWt>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
