### ISSUE TITLE
Error when opening BF4

### ISSUE THREAD

**Issue by Flandyn** [GalaxyEham/FrostyToolSuite#138]
When I try to open BF4 in Frosty, it gives this error:

```
Object reference not set to an instance of an object.

   at FrostySdk.hbDInlQMRUGMPLqYDjQOEVHDfCQ.XwOIxyWpUEiVTFFKIshSNmsIqjH()
   at FrostyEditor.Windows.SplashWindow.<>c__DisplayClass4_0.<GrXReLNcPwvjmgYMnS>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyEditor.Windows.SplashWindow.<GrXReLNcPwvjmgYMnS>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyEditor.Windows.SplashWindow.<uoXijTkQlmJBHBSJmBhjosVNmweNSgwSHFm>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by GalaxyEham** [comment]
The only thing I can suggest is repair ur game, where it appears to be crashing isnt really somewhere it would normally,unless the data it was trying to read was bad.

**Comment by Flandyn** [comment]
I repaired and updated, and now it crashes when loading win32/levels/sp/sp_suez/sp_suez instead of instantly crashing

**Comment by GalaxyEham** [comment]
well not much more i can say, it works fine here, so the issue can only be at your end.
