### ISSUE TITLE
Could not find file 'C:\Users\(Name)\Desktop\Frosty\FrostModManager.ini'.

### ISSUE THREAD

**Issue by Sttahl** [GalaxyEham/FrostyToolSuite#143]
Could not find file 'C:\Users\Sttahl\Desktop\Frosty\FrostyModManager.ini'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at FrostyModManager.Config.TdgBnIYnAePNrbsFTiEwqlkMaKthejStr(String aWGWfokCnPwoISBTkqSSVVKELaeEuApwXiqmSH)
   at FrostyModManager.MainWindow.bncNbrbUhsNtasOwiRT(Object QpxpJEYByScUPTcjxFpEhQPT, EventArgs LrPiUbEsjnBGjVvWkjJuwxoEURfvWKWAPEqnD)
   at System.Windows.Window.OnContentRendered(EventArgs e)
   at System.Windows.Window.<PostContentRendered>b__202_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

( am posting the paste of what it gives me when it crashes since I can't seem to find a crashlog.txt file. also keep in mind that this happens when I try and set the exe file for Star Wars Battlefront II when I first open the program like it asks )

**Comment by GalaxyEham** [comment]
access permissions, u either didnt extract from the zip, or frosty does not have the permissions to write to the above location, you will need to fix it at your end.

**Comment by Sttahl** [comment]
Fixed it up. I just didn't extract it to the correct place. I needed to extract it to the same area of files where the EXE was located for the game.

**Comment by GalaxyEham** [comment]
No you actually don't, I dont even have them on the same drive what so ever. Its your permissions.
