### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by TaniFC** [GalaxyEham/FrostyToolSuite#15]
After i edited a .dds texture with gimp and want to import these new file with FE this message apears: 
(WARNING) Failed to import C:\Users\Jonatan\Desktop\FrostyEditor\jersey_21_3_0_color.dds. Format must be SRGB variant
How is it possible to edit the dds graphic files in a correct way?

**Comment by francoism90** [comment]
Follow the main topic here: http://www.moddingway.com/forums/thread-30176.html
See others discussing the same thing.

**Comment by Pair20002000** [comment]
https://www.photobox.co.uk/my/photo/full?photo_id=9965436950

i dont know what is the problem

**Comment by GalaxyEham** [comment]
Yeah I dunno either since that link doesn't show anything but an ad for photobox, so I cant see what ur referring to.

**Comment by Pair20002000** [comment]
when i open frostyediter   give me this error

Access to the path 'E:\Origin\FIFA 17\data\win32\chants_full.sb' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileSystemRights rights, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateFromFile(String path, FileMode mode, String mapName, Int64 capacity, MemoryMappedFileAccess access)
   at FrostySdk.Managers.AssetManager.Initialize(Boolean additionalStartup)
   at FrostyEditor.Windows.SplashWindow.<>c__DisplayClass3_0.<LoadData>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyEditor.Windows.SplashWindow.<LoadData>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyEditor.Windows.SplashWindow.<Window_Loaded>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Pair20002000** [comment]
the same massage when open frosty manager

**Comment by GalaxyEham** [comment]
Please dont post ur issue everywhere, it makes me less inclined to actually try and help, especially when you hijack other peoples issues.
