### ISSUE TITLE
export

### ISSUE THREAD

**Issue by savinpvtmike** [GalaxyEham/FrostyToolSuite#16]
when i export a character model from star wars battlefront i get this and the program crashes 
Object reference not set to an instance of an object.

   at FrostySdk.Managers.AssetManager.GetAsset(AssetEntry entry)
   at FrostyEditor.Controls.FBXExporter.FBXCreateSkeleton(FbxScene scene, String skeleton, List`1& boneNodes)
   at FrostyEditor.Controls.FBXExporter.ExportFBX(MeshSet meshSet, String filename, String fbxVersion, String units, String skeleton, String fileType)
   at FrostyEditor.Controls.FrostyMeshSetEditor.<>c__DisplayClass19_2.<ExportButton_Click>b__1()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyEditor.Controls.FrostyMeshSetEditor.<ExportButton_Click>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by savinpvtmike** [comment]
now ik i have to select a skeleton but what do i pick for a stormtrooper?

**Comment by GalaxyEham** [comment]
whichever skeleton the stormtrooper mesh uses, basically I cant tell you this information, you have to find it, I dont know game specific details.
