### ISSUE TITLE
Frosty Mod Manager v1.0.5.7 (Unhandled Exception Has Occurred)

### ISSUE THREAD

**Issue by Spartan117B01** [GalaxyEham/FrostyToolSuite#175]
Game: Star Wars Battlefront 1 (2015)

Frosty Message: One ore more symbolic links could not be created, please restart tool as Administrator.

   at Frosty.ModSupport.FrostyModExecutor.<>c__DisplayClass29_0.<Run>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.<Run>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<launchButton_Click>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Notes: I'm the administrator of this system and setting this via compatibility options yields the same error. I have full ownership of said folders. Restarting system doesn't solve the problem. Disabled all mods and I still get this error. Frosty is also not creating the ModData folder and manual creation leads to Frosty removing the folder so it is acceptable to the mod manager. bcrypt.dll is not present in the games directory or the mod managers folder.

**Comment by MohamedElhoseny** [comment]
adapt your game folder permissions so frosty mod manager can access it and read & write files on game folder
