### ISSUE TITLE
Frosty Editor crashes every time I press import button

### ISSUE THREAD

**Issue by ELAD1010** [GalaxyEham/FrostyToolSuite#182]
When I click the import button the frosty editor exits.
the crash log is:
Illegal characters in path.

   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.DirectoryInfo.Init(String path, Boolean checkHost)
   at FrostyEditor.Controls.FrostyOpenFileDialog..ctor(String title, String filter, String inKey)
   at FrostyEditor.MainWindow.<contextMenuImportAsset_Click>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by OCDEngineerBoy** [comment]
Since the error message does say "illegal characters in path", is there non ASCII characters (like Chinese, Russian, German word with Umlaut) in the game path?
