### ISSUE TITLE
I'm dealing with an issue

### ISSUE THREAD

**Issue by TanyaeNorth** [GalaxyEham/FrostyToolSuite#28]
Whenever I run the frosty editor or manager on swbf it will load the interface but when I launch the game it crashes and runs into an issue

here is what the crash says

Could not find a part of the path 'D:\Program Files (x86)\Origin Games\STAR WARS Battlefront\\moddata\patch\win32/xp_offline/xp_offline/cas.cat'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName)
   at Frosty.ModSupport.FrostyModExecutor.<>c__DisplayClass17_0.<Run>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.<Run>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyEditor.MainWindow.<launchButton_Click>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by TanyaeNorth** [comment]
I found the issue but I need someones help
If you have the frosty editor and it is working for you please give me the folder called ModData
and send it to me by attaching files if there are any further problems contact me here
TanyaeNorth@gmail.com
Please help me out I really want to use the frosty editor

**Comment by GalaxyEham** [comment]
What? ModData is created by the mod manager, you should not be using one that someone sends u as it contains the mods already applied, the issue u have is a permissions problem. Delete the bcrypt.dll and ModData directory thats already present in ur game directory and try again.

**Comment by TanyaeNorth** [comment]
Thank you so much, you're a lifesaver!
Sorry for being such a pain!

**Comment by TanyaeNorth** [comment]
Just wondering,
After reinstalling the manager and editor will show however when I launch
the editor or the manager the game won't show up?

If you also have a fix for this I would deeply appreciate it
Thanks
