### ISSUE TITLE
an unhandled exception has ocurred

### ISSUE THREAD

**Issue by lololp0909** [GalaxyEham/FrostyToolSuite#3]
everytime i try to add a mod i receive a message saying "an unhandled exception has ocurred"  and then the mod manager closes

**Comment by GalaxyEham** [comment]
If you are not running v1.01b or later, then please upgrade and paste the actual error message in here.

**Comment by GalaxyEham** [comment]
I havent heard back from you in a while, so im going to close this issue, if there are any issues outstanding please open a new issue

**Comment by Nasr-Ezzo** [comment]
everytime i try to add a mod i receive a message saying "an unhandled exception has ocurred" and then the mod manager closes    please help

**Comment by crb2442** [comment]
Method not found: '!!0[] System.Array.Empty()'.

   at FrostyModManager.MainWindow.<>c__DisplayClass25_0.<InstallMods>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<InstallMods>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

I believe this is the error message they were also referring to. I am running Win7 Pro 64bit, any other info you need let me know. I've tried this from the game directory and another directory and with 2 seperate simple mods.
