### ISSUE TITLE
Can't get any of frosty tools to work ! 

### ISSUE THREAD

**Issue by DawnbreakerX** [GalaxyEham/FrostyToolSuite#39]
Hi there , i can't get any of frosty tools to work cuz am facing these errors which pops up when i try to load FIFA18.exe and here is my crashlog for Frosty Tool Editor , 

Object reference not set to an instance of an object.

   at Frosty.Controls.FrostyProfile.Validate(String value)
   at FrostyEditor.Windows.SplashWindow.<Window_Loaded>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Here is the other one with Frosty Tool Manger , 

Object reference not set to an instance of an object.

   at Frosty.Controls.FrostyProfile.Validate(String value)
   at FrostyModManager.MainWindow.FrostyWindow_FrostyLoaded(Object sender, EventArgs e)
   at System.Windows.Window.OnContentRendered(EventArgs e)
   at System.Windows.Window.<PostContentRendered>b__198_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

- I believe that there is no one will help me as you Galaxyman can do cuz i have been searching for any solution for my errors and i couldn't found any help and i can't enjoy your tools properly so please help and thanks for reading this :)

**Comment by Lucadergro** [comment]
I have the same issue. Please help me !!!

**Comment by Dextro21** [comment]
have the same error

**Comment by AmlanNaskar** [comment]
I tried all possible soln...now the last thing i am gonna do is format..

**Comment by GalaxyEham** [comment]
Please answer the following questions.

1. Where is the game located? please paste the entire path to the game executable
2. What operating system version are you using? list the entire version aka. Windows 10 Home Edition
3. Have you tried running the editor/mod manager as admin?
4. Have you taken full control and ownership of the  game folder?
5. What language/regional settings is your operating system set to? Is it something other than english?

**Comment by jaiy2kkumar** [comment]
G:\origin games\FIFA 18
Windows 10 home edition
yes i tried running the editor and manager as admin
yes i have taken full control of the ownership of the game folder
lanuage is english regional settings is india
![fifa 18 error](https://user-images.githubusercontent.com/34616815/34077225-72796b76-e324-11e7-84e7-81071bcbfb29.jpg)

**Comment by GalaxyEham** [comment]
Ok thats a different error, which is a known issue that will be resolved in the next update. Does that mean ur initial issue is solved?
