### ISSUE TITLE
Value cannot be null, paramter name: buffer error, Frosty Mod Manager

### ISSUE THREAD

**Issue by BuddyBlue** [GalaxyEham/FrostyToolSuite#40]
Hi, when trying to launch Mass Effect Andromeda on Windows 10 through the Frosty Mod Manager, I get this error:

> Value cannot be null.
Parameter name: buffer

   at System.Security.Cryptography.HashAlgorithm.ComputeHash(Byte[] buffer)
   at FrostySdk.Utils.GenerateSha1(Byte[] buffer)
   at Frosty.ModSupport.FrostyModExecutor.<>c__DisplayClass17_0.<Run>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.<Run>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

> 

If I just try to open the editor I get this:

> Value cannot be null.
Parameter name: key

   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at FrostySdk.ProfilesLibrary.get_SDKFilename()
   at FrostySdk.TypeLibrary.Initialize()
   at FrostyEditor.Windows.SplashWindow.<Window_Loaded>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate 

catchHandler)>

The game runs fine on it's own. Can anyone help? Thank you very much!

**Comment by GalaxyEham** [comment]
Check the profiles directory in the Frosty Mod Manager/Editor location, make sure there is a MassEffectSDK.dll located in there, I have had at least on user report that their AV removed the file due to a false report.

Also delete your ini file (Mod Manager/Editor ini) and try picking the exe again. Appears you might have modified the ini after, or something modified it, the exe name must not be renamed from MassEffectAndromeda.exe (and the entry in the ini must not change)

**Comment by BuddyBlue** [comment]
Thanks for the reply! I checked and I do have the MassEffectSDK.dll

My ini for the editor is fine, but I don't actually have an ini file for The Mod Manager. Also now when I try to start Mod Manager it won't open at all, and when I try to start the Editor it runs through its loading process but then crashes when it gets to loading localized strings. When I say crashed I mean I get the message "Frosty Editor" has stopped working.

Thanks for your help!

**Comment by BuddyBlue** [comment]
Hi, both programs open now, and the editor no longer gives me an error when opening. The Mod Manager still gives me the same error when trying to create a mod data path.

**Comment by BuddyBlue** [comment]
When the editor tries to create the mod data path I get this notice:

The requested operation requires elevation

   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Frosty.ModSupport.FrostyModExecutor.​‫⁬‫⁬⁮⁫​‫‭‮‌‌⁬‏‏⁭‏‫⁬‍⁭‪‭⁫‮⁫‭‬⁭⁯‎​‍‏⁫‫‏‏⁫‮(String , String , Boolean , Boolean )
   at Frosty.ModSupport.FrostyModExecutor.‪‭⁭‮⁯‍‪‬‏⁬⁫‬⁭‮⁬‬⁪⁮‮‌⁮‏‎⁪‮⁭⁭⁫⁫‬‎⁬​‮⁫‎‭‎‪⁬‮.​‌⁪‌‍‮‏⁬⁭‮‬‍‭⁬‬⁬‌‏‪⁪⁬⁫‪‎‮⁪‍‪⁭‮‎‭⁯‮⁭‮‮‌‏⁯‮()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Frosty.ModSupport.FrostyModExecutor.$~2HT;$\,N57~NAtrb\[0d7 xN\..MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyEditor.MainWindow.<launchButton_Click>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
