### ISSUE TITLE
Error when fifa 18 has been update update

### ISSUE THREAD

**Issue by jediProgramer** [GalaxyEham/FrostyToolSuite#44]
Could not find a part of the path 'C:\Program Files (x86)\Origin Games\FIFA 18\\moddata\patch\win32/superbundlelayout/fifa_installpackage_00/en/cas.cat'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName)
   at Frosty.ModSupport.FrostyModExecutor.⁯​‍⁭‮‬⁪‮‬⁯⁪⁯⁮‭‎‮⁬‮‏‬⁯​‫⁪​‍‮‮‍⁮⁭‭⁭​⁭‪⁫⁫⁮‏‮.‭‍⁫⁪‬⁪⁬‪‪‏​‪⁬⁭⁭‌⁯⁭⁮⁭‌‪‪‬‏⁫‍⁪⁭⁫‌‪⁬‏​‮⁫⁬‌‎‮()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.PL/4V#5m#OJ3zFX4X!nL8 z}(.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GalaxyEham** [comment]
Delete the ModData directory in the Fifa18 game directory, Unfortunately fifa18 does not update the internal patch version when they release an update, so the mod manager does not know an update has occurred, leaving things in an inconsistent state. Deleting the ModData directory should resolve this.
