### ISSUE TITLE
Frosty Editor fifa 18 helpp

### ISSUE THREAD

**Issue by Lexa028** [GalaxyEham/FrostyToolSuite#49]
Method not found: '!!0[] System.Array.Empty()'.

   at FrostySdk.Managers.AssetManager.⁪‪‫‌⁬‭⁮‪⁭‪‬⁬‏⁪‪‬⁭⁪​‏⁬⁬​‎‮‌⁮‍‏‍‎‮⁭‫‬‌‮⁬⁮‮()
   at FrostySdk.Managers.AssetManager.Initialize(Boolean additionalStartup)
   at FrostyEditor.Windows.SplashWindow.<>c__DisplayClass4_0.<LoadData>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyEditor.Windows.SplashWindow.<LoadData>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyEditor.Windows.SplashWindow.<Window_Loaded>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GalaxyEham** [comment]
Upgrade ur .NET Framework. 4.6.1 or later
