### ISSUE TITLE
"ModData" folder not created

### ISSUE THREAD

**Issue by Alegend27** [GalaxyEham/FrostyToolSuite#5]
Hi when I choose a game executable, the ModData file is not created and I later get this error:

Empty path name is not legal.

   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at FrostySdk.FileSystem.ProcessLayouts()
   at FrostyModManager.MainWindow.<launchButton_Click>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

I hope someone can help me out, thanks!

**Comment by GalaxyEham** [comment]
Are u using the mod manager thats packaged with the HEROBLAST mod?

**Comment by GalaxyEham** [comment]
Closing this issue as I have not heard back from you in 7 days
