### ISSUE TITLE
Method not found error with mod manager.

### ISSUE THREAD

**Issue by crb2442** [GalaxyEham/FrostyToolSuite#50]
Method not found: '!!0[] System.Array.Empty()'.

   at FrostyModManager.MainWindow.<>c__DisplayClass25_0.<InstallMods>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<InstallMods>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

I get this error after successfully launching the manager, but when I load a mod into the manager. I am running Win7 Pro 64bit, any other info you need let me know. I've tried this from the game directory and another directory and with 2 seperate simple mods. I have also tried loading each of them archived and unarchived.

Edit: Forgot to mention the game, Mass Effect Andromeda.

**Comment by GalaxyEham** [comment]
Upgrade your .NET Framework to 4.6.1 or higher

**Comment by crb2442** [comment]
I'll try that, just checked mine and noticed it's still at 4.5.2. Damn microsoft for stopping support for Win 7, lol.
