### ISSUE TITLE
Unexpected Exception has occured

### ISSUE THREAD

**Issue by Aketsuki** [GalaxyEham/FrostyToolSuite#6]
Hi whenever I try to load my mods I get this message followed by the manager crashing

Access to the path 'cas (2017_05_17 11_43_22 UTC).cat' is denied.

   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Frosty.ModSupport.FrostyModExecutor.IsSamePatch(String modPath)
   at Frosty.ModSupport.FrostyModExecutor.DeleteSelectFiles(String modPath)
   at Frosty.ModSupport.FrostyModExecutor.<>c__DisplayClass17_0.<Run>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.<Run>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<launchButton_Click>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GalaxyEham** [comment]
Go to ur game install directory, right click on it, go to properties, untick readonly, then apply to all files and subfolders, dont worry if the tick returns, the setting has applied, then try again

**Comment by Aketsuki** [comment]
That seems to have fixed it, thanks!
