### ISSUE TITLE
FMM cant install any mods

### ISSUE THREAD

**Issue by Malin20** [GalaxyEham/FrostyToolSuite#60]
When i click on launch there is an error:
Value cannot be null.
Parameter name: value

   at System.Security.Cryptography.AesCryptoServiceProvider.set_Key(Byte[] value)
   at FrostySdk.FileSystem.‫‭‌‭‫‬⁪‏‭‎⁮⁯‪‎‎‫⁪‏‫⁭⁭‍‍⁯‍⁬‫‫‌‬⁪‍‏⁮⁫​‏⁮‌⁫‮(Byte[] )
   at FrostySdk.FileSystem.Initialize(Byte[] key)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GalaxyEham** [comment]
Use the latest version, 1.0.3alpha4 had a known issue with requiring an encryption key even for just applying mods, this has since been rectified.
