### ISSUE TITLE
Frosty Editor error 

### ISSUE THREAD

**Issue by osamakahn1** [GalaxyEham/FrostyToolSuite#73]
When I load a mode in Frosty Editor this error appear and close the editor 

Object reference not set to an instance of an object.

   at FrostySdk.Managers.AssetEntry.get_IsIndirectlyModified()
   at FrostyEditor.Controls.FrostyDataExplorer.UpdateTreeView()
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at FrostyEditor.MainWindow.<openModMenuItem_Click>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ThamerD** [comment]
I've had this same error when I tried using the editor for Dragon Age: Inquisition.
I tried an older version (1.0.3.1) and it worked.
