### ISSUE TITLE
An unhauled exception has occured

### ISSUE THREAD

**Issue by Kelochie** [GalaxyEham/FrostyToolSuite#79]
Value cannot be null.
Parameter name: value

   at System.Security.Cryptography.AesCryptoServiceProvider.set_Key(Byte[] value)
   at FrostySdk.FileSystem.⁪‌⁭‌‫‫‏⁮‮⁭‎‫⁬‪⁭⁭⁭⁫‮⁬⁫‌‍‏‍‮⁯‫‎‮‬⁫‪‪‮‫‮⁮‪‬‮(Byte[] )
   at FrostySdk.FileSystem.Initialize(Byte[] key)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object a

**Comment by sebastiancastro8** [comment]
Me pasa lo mismo

**Comment by GalaxyEham** [comment]
Duplicate
