### ISSUE TITLE
An unhauled exception has occured

### ISSUE THREAD

**Issue by DimaPirus** [GalaxyEham/FrostyToolSuite#82]
Value cannot be null.
Parameter name: value

at System.Security.Cryptography.AesCryptoServiceProvider.set_Key(Byte[] value)
at FrostySdk.FileSystem.⁪‌⁭‌‫‫‏⁮‮⁭‎‫⁬‪⁭⁭⁭⁫‮⁬⁫‌‍‏‍‮⁯‫‎‮‬⁫‪‪‮‫‮⁮‪‬‮(Byte[] )
at FrostySdk.FileSystem.Initialize(Byte[] key)
at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object a

**Comment by Sachints7** [comment]
I have the same issue

**Comment by D-Tom** [comment]
Same

**Comment by GalaxyEham** [comment]
Duplicate
