### ISSUE TITLE
Mod manager fucking eror dont working

### ISSUE THREAD

**Issue by durakos** [GalaxyEham/FrostyToolSuite#85]
Frosty Mod Manager eror dont working pleas fix

**Comment by durakos** [comment]
Method not found: '!!0[] System.Array.Empty()'.

   at Frosty.ModSupport.FrostyModExecutor.⁪‮⁫⁮⁭‮‌‫⁮⁫‏⁫‫‌⁮‬‭‏‮⁯‬‎‌‭‮‏⁯⁯‏‌‪⁭⁯⁪⁮‭‮‬‫‌‮.⁯​⁬‫​‍​⁭‬⁮‭⁮‎‏‪⁬‎⁮‪‏‪⁬‬‌‮‎​‌‍⁯‪‮​⁪‭‍‭‪‬‍‮()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.'g{iqT;PR5)>:JK(mxeNr/JD.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler

**Comment by GalaxyEham** [comment]
Dont appreciate profanity
