### ISSUE TITLE
Cant use any mods!

### ISSUE THREAD

**Issue by jamoritch7** [GalaxyEham/FrostyToolSuite#89]
Using Frosty Mod Manager on Fifa 18 and getting the following when using any mod. 

Object reference not set to an instance of an object.

   at Frosty.ModSupport.FrostyModExecutor.⁯​‍⁭‮‬⁪‮‬⁯⁪⁯⁮‭‎‮⁬‮‏‬⁯​‫⁪​‍‮‮‍⁮⁭‭⁭​⁭‪⁫⁫⁮‏‮.‭‍⁫⁪‬⁪⁬‪‪‏​‪⁬⁭⁭‌⁯⁭⁮⁭‌‪‪‬‏⁫‍⁪⁭⁫‌‪⁬‏​‮⁫⁬‌‎‮()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.PL/4V#5m#OJ3zFX4X!nL8 z}(.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lee170** [comment]
I get the same error with Star Wars Battlefront 2.  Tried Frosty 1.0.4.5, then downgraded and tried 1.0.4.2 since that was the version released prior to the mods I was using.  Both versions throw same error, and on several mods.
