### ISSUE TITLE
Cannot launch fifa 18. Fresh install of the game and FrostyEditor

### ISSUE THREAD

**Issue by rabbitofdeth** [GalaxyEham/FrostyToolSuite#91]
Could not find a part of the path 'C:\Program Files (x86)\Origin Games\FIFA 18\\moddata\patch\win32/superbundlelayout/fifa_installpackage_00/en/cas.cat'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName)
   at Frosty.ModSupport.FrostyModExecutor.?????????????????????????????????????????.?????????????????????????????????????????()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.lPlMd\*@hVbE\,4\&u54p7My6\]\[!.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyEditor.MainWindow.<launchButton_Click>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

How can i find the cas.cat file to launch? It is missing from the installpackage_00

**Comment by linuxfreak90** [comment]
This happens after updates, not something that can be fixed I think, links may be changed.

Anyway to fix this issue, delete the folder **..\Origin Games\FIFA 18\ModData**
