### ISSUE TITLE
An unhandled exception has ocurred

### ISSUE THREAD

**Issue by rahmanmh** [GalaxyEham/FrostyToolSuite#93]
i have issue right down below! pls help!

Value cannot be null.
Parameter name: value

   at System.Security.Cryptography.AesCryptoServiceProvider.set_Key(Byte[] value)
   at FrostySdk.FileSystem.‫‭‌‭‫‬⁪‏‭‎⁮⁯‪‎‎‫⁪‏‫⁭⁭‍‍⁯‍⁬‫‫‌‬⁪‍‏⁮⁫​‏⁮‌⁫‮(Byte[] )
   at FrostySdk.FileSystem.Initialize(Byte[] key)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GalaxyEham** [comment]
Duplicate
