### ISSUE TITLE
FIFA Infinity Patch 18 (v.2.0) - An unhandled exception has occurred 

### ISSUE THREAD

**Issue by BogdanModolea** [GalaxyEham/FrostyToolSuite#94]
Value cannot be null.
Parameter name: value

   at System.Security.Cryptography.AesCryptoServiceProvider.set_Key(Byte[] value)
   at FrostySdk.FileSystem.‫‭‌‭‫‬⁪‏‭‎⁮⁯‪‎‎‫⁪‏‫⁭⁭‍‍⁯‍⁬‫‫‌‬⁪‍‏⁮⁫​‏⁮‌⁫‮(Byte[] )
   at FrostySdk.FileSystem.Initialize(Byte[] key)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by GalaxyEham** [comment]
Since this appears to be a problem with a mod, report to the mod owner.
