### ISSUE TITLE
An unhandled exception has occurred

### ISSUE THREAD

**Issue by peeweenewman** [GalaxyEham/FrostyToolSuite#95]
I have the latest version, and I have tried it without any mods, and this pops up every time. is there a way to fix this?

The requested operation requires elevation

   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Frosty.ModSupport.FrostyModExecutor.‏‪‪‌⁭‌⁭​‌‎‮⁮‏⁮‪⁫⁯‏⁫⁭⁪‍⁭⁯⁫⁭‭⁪‬‍‬⁯‍⁯‎‭‌‫⁬‮(String , String , Boolean , Boolean )
   at Frosty.ModSupport.FrostyModExecutor.⁪‍‌⁮⁪‏‮‮⁪‬‭​‪⁫‬⁪⁭​‮‎‪‏‍‏‭​⁯⁬⁪‏⁫‌‫‫‮‏‪‫‫⁬‮.‏‬‎‍⁯⁪⁮‌⁫​⁭⁪‬‏⁭⁭‬⁯‬⁭‎⁬‍‫⁭‭‏‪​‎⁮⁬​‮‫‌‬‏‫‭‮()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.HKJ\*6@wc\]@%1Y3\\aUCr! MXH%.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by peeweenewman** [comment]
and I gave it administrative permission.

**Comment by sdfghc** [comment]
i need help

**Comment by peeweenewman** [comment]
I still have not figured it out. I need some help too. Anyone?
