### ISSUE TITLE
How can I fix this error it gives me before crashing on launch? 

### ISSUE THREAD

**Issue by aaseiler** [GalaxyEham/FrostyToolSuite#97]
Could not find a part of the path 'D:\Program Files (x86)\Origin Games\STAR WARS Battlefront II\\moddata\patch\win32/installation/initialexperience/cas.cat'.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName)
   at Frosty.ModSupport.FrostyModExecutor.⁪‍‌⁮⁪‏‮‮⁪‬‭​‪⁫‬⁪⁭​‮‎‪‏‍‏‭​⁯⁬⁪‏⁫‌‫‫‮‏‪‫‫⁬‮.‏‬‎‍⁯⁪⁮‌⁫​⁭⁪‬‏⁭⁭‬⁯‬⁭‎⁬‍‫⁭‭‏‪​‎⁮⁬​‮‫‌‬‏‫‭‮()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.HKJ\*6@wc\]@%1Y3\\aUCr! MXH%.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lehabibi** [comment]
I get similar errors with NFS2016 


Object reference not set to an instance of an object.

   at Frosty.ModSupport.FrostyModExecutor.⁪‮⁫⁮⁭‮‌‫⁮⁫‏⁫‫‌⁮‬‭‏‮⁯‬‎‌‭‮‏⁯⁯‏‌‪⁭⁯⁪⁮‭‮‬‫‌‮.⁯​⁬‫​‍​⁭‬⁮‭⁮‎‏‪⁬‎⁮‪‏‪⁬‬‌‮‎​‌‍⁯‪‮​⁪‭‍‭‪‬‍‮()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Frosty.ModSupport.FrostyModExecutor.'g{iqT;PR5)>:JK(mxeNr/JD.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FrostyModManager.MainWindow.<launchButton_Click>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
